# Aqui iremos nomear adequadamente nosso pipeline (fluxo de trabalho)
name: Primeiro workflow
# aqui iremos listar os eventos (gatilhos) que disparam o pipeline.
on:
  push: 
    branches:
      - main
      - master
      - developer
  pull_request:
    branches: [main, master, developer, hotfix]
# quais trabalhos a serem executados pelo workflow?  
jobs:
  Trabalho1:
    name: Fluxo 1
    needs: Trabalho2
    runs-on: ubuntu-latest
    # agora irei programar os passos do script 
    steps:
      - name: Passo 1
        run: echo "Executando o primeiro passo"
      - name: Passo 2
        run: echo "Executando o segundo passo"
      - name: Passo 3
        run: echo "Executando o terceiro passo"
  Trabalho2:
    name: Fluxo 2
    runs-on: ubuntu-latest
    # agora irei programar mais outra sequencia de passos do script 
    steps:
      - name: Passo 4
        run: echo "Executando o quarto passo"
      - name: Passo 5
        run: echo "Executando o quinto passo"
      - name: Passo 6
        run: echo "Executando o sexto passo"
  Trabalho3:
    name: Fluxo 3
    needs: Trabalho1
    runs-on: ubuntu-latest
    # agora irei programar os passos do script 
    steps:
      - name: Passo 7
        run: echo "Executando o setimo passo"
      - name: Passo 8
        run: echo "Executando o oitavo passo"
      - name: Passo 9
        run: echo "Executando o novo passo"        
    

